### ISSUE TITLE
Error on long running migration

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/CDP4-WebServices-Community-Edition#183]
### Description
At the end of the migration seeding process on the CDP4 server the Webservices threw an error displayed in the logs, but all the models seemed to have been working anyway afterwards; this needs further investigation.
```
2021-01-29 14:34:20.5310|ERROR|CDP4WebServices.API.Modules.ExchangeFileImportyApi+<SeedDataStore>d__109.MoveNext|Unable to dump the datastore. 57014: canceling statement due to statement timeout    at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlDataReader.<NextResult>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<ExecuteReaderAsync>d__102.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at CDP4WebServices.API.Services.DataStore.DataStoreController.CloneDataStore() in C:\Users\Cozmin Velciu\Documents\Repositories\RHEA\CDP4-WebServices-Community-Edition\CDP4WebServices.API\Services\DataStore\DataStoreController.cs:line 49
   at CDP4WebServices.API.Modules.ExchangeFileImportyApi.<SeedDataStore>d__109.MoveNext() in C:\Users\Cozmin Velciu\Documents\Repositories\RHEA\CDP4-WebServices-Community-Edition\CDP4WebServices.API\Modules\10-25\ExchangeFileImportyApi.cs:line 312
```

The seeding process on the server took a very long time (with no user feedback during the process): on my machine it was ~1h for 28 models:
```
13:40:12 Export operation start
13:40:12 Pushing data to http://localhost:5000/Data/Exchange
14:34:20 Export operation end
```

**Comment by cozminvelciu** [comment]
Issue created as a result of [this](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/issues/93).
